### ISSUE TITLE
Are you sure ZC550KL has a battery of 3000mAh?

### ISSUE THREAD

**Issue by dxhisboy** [audahadi/android_device_asus_Z010D#1]
I think I have a ZC550KL with 4850mAh battery, and also, what is the progress? I also tried to compile a cm 4 ZC550KL, but failed.

**Comment by audahadi** [comment]
Sensor / camera /security break

**Comment by dxhisboy** [comment]
Will it enter a boot loop? I just compiled it and it entered a boot loop.

**Comment by audahadi** [comment]
No boot loop.. Logcat?

**Comment by audahadi** [comment]
For vendor use cm13 redo branch

**Comment by dxhisboy** [comment]
Since the keymaster.mdt is installed in /etc/firmware,I tried to link it to /system/vendor/firmware/keymaster/keymaster.mdt and it works.

**Comment by audahadi** [comment]
Asus put in there.. Most other device in vendor/firmware
